os: 
  - "linux"

language: node_js

node_js:
  - "8"

cache: yarn

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install xvfb libxtst6 libxss1 libgtk2.0-0 -y
  - sudo apt-get install libnss3 libasound2 libgconf-2-4 -y
  - cd nativeApp
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
script:
  - node --version
  - npm --version
  - yarn --version
  - yarn install
  - yarn run test
