os: 
  - "linux"

language: node_js

node_js:
  - "8"

cache: yarn

addons:
  apt:
    packages:
      - xvfb
      
before_install:
  - cd nativeApp
  
before_script:
  - "export DISPLAY=:99.0"
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - node --version
  - npm --version
  - yarn --version
  - yarn install
  - yarn run test
