os: 
  - "linux"

language: node_js

node_js:
  - "8"

cache: yarn

    
before_install:
  - cd nativeApp
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - pwd


script:
  - node --version
  - npm --version
  - yarn --version
  - yarn install
  - yarn run test
