version: '2'
services:
  my_floating_video_panels:
    build: ./
    volumes:
      - ./:/home/code
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
    environment:
      DISPLAY: unix$DISPLAY
      te2e: "npm run test:e2e"
      start: "npm run start" 
    network_mode: 'host'
    working_dir: /home/code
    tty: true 